name: say-hello-testbash-actions
run-name: ${{ github.actor }} Hello Testbash!
on: [push]
jobs:
  hello-testbash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Testbash!"

  run-unit-test:
    runs-on: ubuntu-latest
    steps:
      - run: cd ./code/testbash/todo_app/src/webapp/api
      - run: npm install
      - run: npm run test
